name: Publish to BCR
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: Release tag name (e.g. "v1.0.0")
        required: true
        type: string
jobs:
  publish:
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@79e6de0c555784ad44047d0d60eb1d7df799ce8b # v0.2.1
    permissions:
      contents: write
      id-token: write
      attestations: write
    with:
      tag_name: ${{ inputs.tag_name || github.ref_name }}
      registry_fork: jjmaestro/bazel-central-registry
    secrets:
      publish_token: ${{ secrets.PUBLISH_TOKEN || secrets.BCR_PUBLISH_TOKEN }}
